import { chromium } from 'playwright'
const b = await chromium.launch({ args:['--use-gl=angle','--ignore-gpu-blocklist','--enable-webgl'] })
const p = await b.newPage({ viewport: { width: 1280, height: 1000 }, deviceScaleFactor: 1.4 })
const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>{ if(m.type()==='error') errs.push('[console] '+m.text()) })
await p.goto('http://localhost:3000/', { waitUntil: 'networkidle' }).catch(()=>{})
await p.waitForTimeout(4000)
await p.click('#wc-cta')
await p.waitForTimeout(1200)
await p.screenshot({ path: '/tmp/wc-c1-top.png' })
await p.evaluate(()=>document.getElementById('wc-overlay').scrollTo(0, 760))
await p.waitForTimeout(400)
await p.screenshot({ path: '/tmp/wc-c1-mid.png' })
console.log('errors:', errs.slice(0,6).join(' | ')||'none')
await b.close()
